name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.6
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
      - name: Lint
        run: cargo clippy
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose